services:
  php:
    build: ./docker/php
    container_name: symfony-php
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    environment:
      PHP_IDE_CONFIG: serverName=cup-score-board.local
      XDEBUG_MODE: debug,develop
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - db

  nginx:
    image: nginx:1.27-alpine
    container_name: symfony-nginx
    ports:
      - "8082:80"
    volumes:
      - ./public:/var/www/html/public:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php

  db:
    image: postgres:16-alpine
    container_name: symfony-db
    environment:
      POSTGRES_DB: symfony
      POSTGRES_USER: symfony
      POSTGRES_PASSWORD: symfony
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
